### ISSUE TITLE
[help] How to define dynamic instance attributes

### ISSUE THREAD

**Issue by murphyslaw** [solnic/virtus#122]
Hello,

I'm having an object, that gets its attributes at runtime dynamically. The problem is, that each instance of that object may have different attributes.

``` ruby
class Content
  include Virtus

  attribute :position
  attribute :title
  # ...

  def initialize(attributes = {})
    attributes.each do |name, value|
      # Inject attributes into current instance.
      instance_eval { class << self; self end }.send(:attribute, name)

      send("#{name}=", value)
    end
  end
end
```

This does not work. The metaclass gets the attribute set, but the setter call to the Content instance in the next line throws an "undefined method" error. When I use "attr_accessor" instead of "attribute" it works as expected, but then I have the problem fetching all attributes.

Sorry, if this is something completely off topic, I would just like to use all the Virtus functionality for the dynamically added instance attributes.

**Comment by kaelumania** [comment]
I ended using the following snippet:

```ruby
class Foo
  include Virtus.model

  attribute :bar, String, default: 'bar'

  def initialize(attributes = {}, *args)
    self.extend(Virtus)

    # redefine static attributes
    attribute_set.merge(self.class.attribute_set)

    # define dynamic attributes
    attributes.keys.each do |name|
      attribute(name) unless attribute_set[name] 
    end

    super
  end
end

foo = Foo.new(bar: 'one', baz: 'two')
foo.bar # one
foo.baz # two
```
