### ISSUE TITLE
MultiParameters

### ISSUE THREAD

**Issue by ismaelga** [solnic/virtus#158]
Is there any way to accept multi parameters for example for date and time?

I haven't read anything about it so I suppose not. If so what do you guys think about adding this as a plugin gem? I have an idea how to implement it but I'm not sure if it will work because I haven't seen much on virtus internals

**Comment by dgilperez** [comment]
@ismaelga how did you eventually approached this?

**Comment by ismaelga** [comment]
@dgilperez I can't remember but I probably changed the form input to get a string instead.

**Comment by maxshelley** [comment]
@dgilperez I just came across this after needing the same thing. How did you handle this? I wrote a little re-former class, https://gist.github.com/maxshelley/6581d8a3897e81493d39, but I'm not sure this was the best way to deal with this. Would love to hear if you found anything better?

**Comment by ismaelga** [comment]
@maxshelley you might want to have a look at https://github.com/datamapper/dm-rails/blob/master/lib/dm-rails/multiparameter_attributes.rb

You will also find a lot of discussion about this feature googling for MultiparameterAttributes

**Comment by joost** [comment]
Thanks @ismaelga. This gist (Google result #1) did the trick for me: https://gist.github.com/sj26/767b29f11fed8a4d13c5

**Comment by sj26** [comment]
I've release a gem based on that gist here:

https://github.com/sj26/virtus-multiparams
