### ISSUE TITLE
Attribute defaults

### ISSUE THREAD

**Issue by fgarcia** [solnic/virtus#252]
Is there any easy way to write Virtus objects where all attributes are by default "String" AND "Private" (but still shown when converted to a hash)?

Regarding private values this was my first thought:

``` ruby
class Foo
  include Virtus.model
  attribute :id, String
  attribute :value, String, :accessor => private
end
```

However while I wanted this:

``` ruby
a = Foo.new(id:"5", value:"5343")
a.value # access error
```

I got a class where the `new` constructor takes 0 arguments

This is more of a support question, if StackOverflow (or somewhere else) is a better place, just point me to the right direction. However I thought it was valuable asking here just to show one way I am trying to use the gem.

**Comment by bguest** [comment]
It would be nice to be able to mark some attributes as imutable, ie you can define them durring initialization, but not after ie:
```ruby
class User
  attribute :user_id, Integer, :accessor => :immutable
  attribute :name, String
end

uu = User.new(:user_id => 33)
uu.user_id  #=> 33
uu.user_id = 10      #error
uu.name = 'Bob'
uu.name  #=> 'Bob'
```
