### ISSUE TITLE
Access parent from embedded model

### ISSUE THREAD

**Issue by simonhildebrandt** [solnic/virtus#281]
For classes like:

```
class Rate
  include Virtus.model
end

class Product
  include Virtus.model
  attribute :rate, Rate
  attribute :name
end
```

...I'd like to be able to collect the product's name from a rate instance embedded inside it. 

Is there an obvious way to do this with Virtus that I'm missing? I imagine it either involving a 'parent' method for models, or some kind of ['embedded_in' syntax like Mongoid](http://mongoid.org/en/mongoid/v3/relations.html#embeds_one).

If this is compatible with the intention of Virtus I'm happy to take a swing at building - if not, any hints at how to work around it would be very welcome.

(And thanks for the awesome gem - we've used it most of our new projects.)

**Comment by cmrichards** [comment]
This is a shame.  Some of the validations on my child objects depend on the field of a parent object (a check bxo).
