### ISSUE TITLE
Virtus 0.5.4 causes rake assets:precompile failure with TypeError: no implicit conversion of Symbol into Integer

### ISSUE THREAD

**Issue by cromwellryan** [solnic/virtus#295]
Latest versions have solved this issue, but for those with legacy dependencies Virtus 0.5.4 and using Ruby 2.0.0.p576 (previous patch levels didn't) causes assets:precompile to fail with: 

```
TypeError: no implicit conversion of Symbol into Integer
/Users/ryan/.rvm/gems/ruby-2.0.0-p576/gems/backports-2.6.7/lib/backports/tools.rb:265:in `[]'
```

[backports:265](https://github.com/marcandre/backports/blob/v2.6.7/lib/backports/tools.rb#L265) shows `options` as a number causing the failure.

Upgrading virtus solves this problem.

**Comment by gaaady** [comment]
upgrading to virtus 1.0.5 solved it for me
