### ISSUE TITLE
Suggestion: DSL for Interdependent Attributes

### ISSUE THREAD

**Issue by Ajedi32** [solnic/virtus#303]
Let's say I have two attributes whose values are directly dependent on one another:

```ruby
class ExampleObject
  include Virtus.model

  attribute :record_id, Integer, default: ->(form, _) { form.record.try(:id) }
  attribute :record, Record, default: ->(form, _) { Record.find_by_id(form.record_id) }
end
```

I want to make it so that not only are the default values of `record_id` and `record` dependant on one another, but updating one value automatically updates the other as well. Currently, I can do that like this:

```ruby
class ExampleObject
  include Virtus.model

  attribute :record_id, Integer, default: ->(form, _) { form.record.try(:id) }
  def record_id= record_id
    super
    reset_attribute(:record)
  end

  attribute :record, Record, default: ->(form, _) { Record.find_by_id(form.record_id) }
  def record= record
    super
    reset_attribute(:record_id)
  end
end
```

I'd like to suggest a DSL for the case above, which expresses my intent more concisely:

```ruby
class ExampleObject
  include Virtus.model

  attribute :record_id, Integer, default: ->(form, _) { form.record.try(:id) }, depends: [:record]
  attribute :record, Record, default: ->(form, _) { Record.find_by_id(form.record_id) }, depends: [:record_id]
end
```

**Comment by solnic** [comment]
Hey, thanks for suggestion. This could be done as virtus plugin. The plan for virtus 2.0 is to simplify it :)

**Comment by Ajedi32** [comment]
Haha. Okay, fair enough. I can definitely understand the need to avoid feature creep.
