### ISSUE TITLE
Support computed properties

### ISSUE THREAD

**Issue by sobrinho** [solnic/virtus#307]
Hi,

What you think about "computed atributes"? Similar to what [Ember.JS](http://emberjs.com/guides/object-model/computed-properties/) and [Backbone.Computed](https://github.com/skaterdav85/backbone-computed-properties#basic-example).

We have a lot of this happening in our application:

``` ruby
class SomeReport
  include Virtus.model

  attribute :user_id, Integer
  attribute :person_id, Integer
  attribute :unit_id, Integer

  delegate :name, :to => :user, :prefix => true
  delegate :name, :to => :person, :prefix => true
  delegate :name, :to => :unit, :prefix => true

  def user
    @user ||= User.find(user_id) if user_id
  end

  def person
    @person ||= Person.find(person_id) if person_id
  end

  def unit
    @unit ||= Unit.find(unit_id) if unit_id
  end
end
```

Note that if you change the user_id/person_id/unit_id value the methods won't change if has be accessed before due to the memoization.

Then we can fix it using something like:

``` ruby
def person_id=(person_id)
  @person = nil
  super
end

def person
  @person ||= Person.find(person_id) if person_id
end
```

We can keep it dry using the concept of computed properties, something like this:

``` ruby
class SomeReport
  include Virtus.model

  attribute :person_id, Integer

  computed_attribute :person, :attributes => :person_id

  def person
    Person.find(person_id) if person_id
  end
end
```

The classical full_name:

``` ruby
class UserReport
  include Virtus.model

  attribute :first_name, String
  attribute :last_name, String

  computed_attribute :full_name, :attributes => %i(first_name last_name)

  def full_name
    "#{first_name} #{last_name}"
  end
end
```

Wdyt?

It may be a overkill, I'm not sure.

**Comment by solnic** [comment]
Sorry, but Virtus is going on a diet and we'll be removing features in 2.0, not adding :) This could be an add-on though.
