### ISSUE TITLE
yield self on #initialize

### ISSUE THREAD

**Issue by vanburg** [solnic/virtus#308]
Is there any strategy, why there's no ``yield self if block_given?`` for #initialize?
https://github.com/solnic/virtus/blob/master/lib/virtus/instance_methods.rb#L16-L19

I can implement this small nice feature, just need to discuss should I, and where to:
- at the beginning
- after attrs set (behave like ActiveRecord::Base#initialize)
- instead of attrs set
- before defaults
- after defaults (looks like the best solution for our case)
- only when no attrs received

BTW, I know I can use Post.new.tap for that ;)

**Comment by pjkelly** [comment]
We're interested in this too and would be happy to help implement.  @solnic - what are your thoughts on this?

**Comment by solnic** [comment]
Can you show me some use cases for that feature? I want reduce functionality of Virtus in its 2.0 version so in general I'm skeptical when it comes to adding new features.

**Comment by pjkelly** [comment]
Our use-case is pretty basic. In some contexts, it's just nicer/prettier to initialize an object using a block-style syntax, instead of a hash.

e.g. instead of this:

``` ruby
AwesomeObject.new(:name => 'John Doe',
                  :age => 25,
                  :bio => 'Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit.',
                  :interests => 'Nulla vitae elit libero, a pharetra augue.',
                  :education => 'Aenean lacinia bibendum nulla sed consectetur.')
```

we'd like to do this:

``` ruby
AwesomeObject.new do |a|
  a.name = 'John Doe'
  a.age = 25
  a.bio = 'Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit.'
  a.interests = 'Nulla vitae elit libero, a pharetra augue.'
  a.education = 'Aenean lacinia bibendum nulla sed consectetur.'
end
```

**Comment by solnic** [comment]
then `tap` is your friend, sorry but that won't be added.

**Comment by pjkelly** [comment]
Fair enough - thanks for the update.
