### ISSUE TITLE
Use ID for determining Model equality

### ISSUE THREAD

**Issue by KaptajnKold** [solnic/virtus#320]
I find it surprising that model equality is determined by object equality. To me, it is part of the semantics of a model (or *an Entity* in the DDD parlance) is that equality is determined by ID. Same ID, same entity.

I propose that an attribute declared with `id: true`, enables this behaviour.

**Comment by solnic** [comment]
You can do `include Equalizer.new(:id)` in your models to achieve that.

**Comment by KaptajnKold** [comment]
Cool :)
