### ISSUE TITLE
nullify_blank with type String fails

### ISSUE THREAD

**Issue by janjiss** [solnic/virtus#324]
Hey there, I have found that nullify_blank option does not work with type of String, please see the gist attached:

https://gist.github.com/janjiss/3a09b4a51c8a54ed05c5

Let me know if this is an intentional behaviour or not. Maybe I can make a PR for this.

**Comment by solnic** [comment]
That's intentional, empty strings are not coerced to nils. You can see discussion in the [PR](https://github.com/solnic/virtus/pull/314) which added this feature.

**Comment by janjiss** [comment]
Alright, that makes sense!
