### ISSUE TITLE
Hash attributes coercion

### ISSUE THREAD

**Issue by jasonenglish** [solnic/virtus#336]
Wondering if it's possible to coerce a hash value to a collection of models.

Example (based on the readme "Hash attributes coercion" section): 
`attribute :results, Hash[String => Array[Person]]`

Given this JSON
```json
{
    "element_count": 60,
    "results": {
        "2015-04-06": [
            {
                "id": 1,
                "name": "Jon Snow"
            }
        ]
    }
}
```

I would like to end up with the MyObject results being a hash of String:Array[Person] values.
`=> #<MyObject:0x007f82049c3e38 @element_count=60, @results=>{"2015-04-06"=>[#<Person:0x007f82049c3e38 @id=1, @name=Jon Snow.....]`

Any ideas on how to achieve this?

**Comment by jasonenglish** [comment]
Ended up just manually doing the coercion

**Comment by dmitry** [comment]
@jasonenglish any points how did you made that?
