### ISSUE TITLE
attributes method doesn't behave as specified in the Readme

### ISSUE THREAD

**Issue by alaibe** [solnic/virtus#352]
Hi
This is the readme:
```ruby
class User
  include Virtus.model

  attribute :name, String
  attribute :age, Integer
  attribute :birthday, DateTime
end

user = User.new(:name => 'Piotr', :age => 31)
user.attributes # => { :name => "Piotr", :age => 31 }
```

This is from my irb

```ruby
class User
  include Virtus.model

  attribute :name, String
  attribute :age, Integer
  attribute :birthday, DateTime
end

user = User.new(:name => 'Piotr', :age => 31)
user.attributes # => { :name => "Piotr", :age => 31, :birthday=>nil }
```

Virtus version: 1.0.5
Ruby version: ruby 2.2.2p95

I would expect `attributes` to not return the birthday
As I am using virtus for form object it causes me problem when I want to do PATCH request

**Comment by zenry** [comment]
Ruby
```ruby
user.attributes.delete_if { |k, v| v.nil? }
```

Rails
```ruby
user.attributes.compact
```

**Comment by alaibe** [comment]
Thx for your answer.

Unfortunately it is not enough
=> you can't set a value to `nil` with this solution

I already have a workaround to make it works (I can post it if you want)

My question is more:
The README is not sync with the behaviour so if

* The readme is correct
=> then there is a problem that need to be fix

* The current behaviour is correct
=> I keep my workaround
=> The readme needs an update

**Comment by booch** [comment]
It'd take some effort to add tracking of which attributes have been set to nil and which have not been set. So I'm going to fix the README to match the behavior.
