### ISSUE TITLE
Mark as unmaintaned

### ISSUE THREAD

**Issue by mensfeld** [solnic/virtus#386]
Let's be clear - @solnic is working on rom and dry - this library had it times and IMHO it would be good to tell community that there are new roads to take.

**Comment by krisleech** [comment]
Would it be worth a "looking for new maintainer" in the README for a while.

**Comment by solnic** [comment]
I'm OK with officially killing the project once we have a robust & stable alternative from the dry-rb world. This means finishing dry-types & dry-struct & dry-validation.
