### ISSUE TITLE
Virtus hogs initialize()

### ISSUE THREAD

**Issue by tomoyoirl** [solnic/virtus#44]
If I `include Virtus` in my class, it adds a method `initialize` to do it's magic. This is mostly a good thing, but it means that I cannot compute and set non-Virtus instance variables at object creation time. I'd like to be able to do this.

**Comment by magicalbanana** [comment]
I know this has been closed for quite sometime now but how would I make it possible that I set an initializer and if no options were passed matching the attribute it uses the default set?

```
def initialize

end

**Comment by solnic** [comment]
Maybe you could override `.new` and handle this logic there.
