### ISSUE TITLE
Writing private attributes from the constructor

### ISSUE THREAD

**Issue by mattwynne** [solnic/virtus#96]
I am finding that a very common use-case for me is that I want to use a virtus object to wrap another object or objects.

I'd like to be able to do this:

```
class PersonPage
  attribute :person, Person, accessor: private

  def age
    "#{person.age} years old"
  end
end
```

I make the `person` attribute private because I don't want it to be part of the public interface of this object, but I do want to be able pass it to the PersonPage's constructor as a named argument. However I've found that when I pass the Person instance that I want to wrap into the PersonPage constructor, it isn't set. I think this is  because the accessor is private. 

I could use the options to set the writer to public, but I don't want to expose a setter as part of the public interface - I just want to be able to set it from the constructor.

Am I using the library wrongly, or should we change it so that even attributes with private setters can be set from the constructor?

**Comment by fgarcia** [comment]
I had a similar confusion with how private attributes work but the allowed_methods solution did not work for me (with and without 'self') :

    def self.allowed_methods
      super - (private_methods + [:age=]).map(&:to_s)
    end

My common use case for private attributes is for attributes that I do not want the user to write like `person.age = 23` but I do want that internal state to be persisted and restored from a database (loaded as a keyword in the constructor). 

My naive initial implementation was like this:

    class PersonPage
      include Virtus

      attribute :name, String
      attribute :age, Integer
      private :age=
    end

But that private statement will break Virtus constructor, ignoring also :age values

I solved this issue by writing an initialize function and set manually the value. Is that the standard way to solve this problem?

**Comment by ta** [comment]
A perhaps slightly more hackish way of having attributes assignable only by mass-assignment:

```ruby
class Model
  include Virtus::Model

  def initialize(args = {})
    super(args)

    # Handle "immutable" attributes
    attribute_set.each do |attribute|
      if attribute.options.fetch(:immutable, false)
        name = attribute.options.fetch(:name)
        define_singleton_method(:"#{name}=") { |_| raise "Attribute #{name} is immutable" }
      end
    end
  end
end

class Post < Model
  attribute :id, Integer, default: nil, immutable: true
end

post = Post.new(id: 1)
# => #<Post:0x00000000024af450 @id=1>
post.id = 2
# => RuntimeError: Attribute id is immutable
```
